# Generated by Django 5.2.7 on 2026-06-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_agent_id_alter_env_id_alter_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Started', 'Started'), ('Finished', 'Finished')], default='Created', max_length=10),
        ),
    ]
